# Generated by Django 5.2.8 on 2025-11-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='agendamento_cliente_90ffda_idx',
            old_name='api_agendam_cliente_4c9918_idx',
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='agendamento_profiss_88209f_idx',
            old_name='api_agendam_profiss_2fc508_idx',
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='agendamento_servico_8715cd_idx',
            old_name='api_agendam_servico_421a92_idx',
        ),
        migrations.RenameIndex(
            model_name='agendamento',
            new_name='agendamento_data_ho_be5bb8_idx',
            old_name='api_agendam_data_ho_2a11dd_idx',
        ),
        migrations.AlterField(
            model_name='profissional',
            name='servicos',
            field=models.ManyToManyField(db_table='profissionais_servicos', related_name='profissionais', to='api.servico'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='agendamento',
            table='agendamentos',
        ),
        migrations.AlterModelTable(
            name='horariotrabalho',
            table='horarios_trabalho',
        ),
        migrations.AlterModelTable(
            name='profissional',
            table='profissionais',
        ),
        migrations.AlterModelTable(
            name='servico',
            table='servicos',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
