# Generated by Django 6.0 on 2026-01-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usuario_username_alter_servico_preco_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='api_usuario',
        ),
    ]
